baseurl = "http://whiskingwell.com/"
languageCode = "en-us"
title = "Whiskingwell"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Whiskingwell - Plantbased cakes and desserts in Singapore"
	description = "Order vegan, glutenfree cakes"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

	[params.rss] 
	   hide = true

	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "logo.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "We bake you **happy**.<br/> Order your **Vegan** cakes now."
		# The icons will be shown if you enter your username
		twitter = ""
		instagram = "@whiskingwell"
		github = ""
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Alexander Edelmann"
		]


	[params.about]
		hide  = false
		title = "We bake you happy with delicious, vegan cakes"
		content = "Vegan simply means plant based food ingredients only. By default in all versions of our cakes, we do not use any form of animal products, egg, dairy product which includes milk, cheese, yoghurt and whey protein. Without all these ingredients, our cakes are 100% Cholesterol Free and as well as Gluten Free too."

	[params.portfolio]
		hide  = false
		title = "Available cakes"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "superstar_front.jpg"
			thumb = "superstar_front.jpg"
			title = "Superstar - Chocolate Cheesecake"
			link  = "post/cake-superstar"
			description = "German classic chocolate crumble cheese cake."

		[[params.portfolio.gallery]]
			image = "darkknight_front.jpg"
			thumb = "darkknight_front.jpg"
			title = "Dark Knight - Chocolate Hazelnut"
			link  = "post/cake-darkknight"
			description = "Chocolate sponge cake with hazelnuts and coating of dark chocolate ganache."


	[params.recentposts]
		hide  = true
		title = "More details about our cakes"

	[params.contact]
		hide  = false
		title = "Order your cake now"
		content = "Orders will only be completed upon confirmation of prepayment after we get in touch with you."
		# This can be exact coordinates or a searchable address in google maps

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "order.whiskingwell@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Full Name"
			email = "Email"
			message = "Your message"
			submit = "Order"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10
